#!/usr/bin/Rscript


#' Function to get an LPJ-GUESS quantity based on a string
#' 
#' NEED to generalise this to deal with other lists of \code{VegQuants}, not just assuming all are LPJ-GUESS
#' 
#' @param quant.str String holding the id of the \code{VegQuant} you want
#' @param verbose Logical, whether or not to announce which \code{VegQuant} has been found
lookupVegQuantity <- function(quant.str, verbose = FALSE){
  
  # check if the quantity we are storing here is already in the list of pre-defined quantities (LAI, Cmass etc)
  # if not use the 'generic' quantity
  this.quantity <- lpj.quantities[[quant.str]]
  
  if(length(this.quantity) != 0) {
    if(verbose) message(paste("Found quantity ", this.quantity@id, sep = ""))
  }   
  else{
    warning(paste("Didn't find a defined VegQuant for", tolower(quant.str), "using generic values for colors, units etc.", sep = " "))
    this.quantity <- lpj.quantities[["generic"]]
  } 
  
  return(this.quantity)
  
}



#' Global scope list of all LPJ-GUESS (and SPITFIRE) quantities defined as \code{VegQuant} object 
#' from the default LPJ-GUESS model config and a few extra.
#'
#' These quantities have sensible colour schemes, long names and cut ranges for standard global runs,
#' but they will likely need to be modified and new ones aded for a specific analysis.
#' Once the package is loaded this is just a standard R list so can be modified and extended as you wish.
#' 
#' @format A list of \code{VegQuant} objects that store meta-data for output variable commonly used from LPJ-GUESS (and LPJ-GUESS-SPITFIRE)
#' @author Matthew Forrest \email{matthew.forrest@@senckenberg.de}
#' @seealso \code{VegQuant}-class
lpj.quantities <- list(
  
  "fraction" = new("VegQuant",
                   id = "fraction",
                   type = "unknown",
                   name = "Fraction",
                   units = "",
                   colours = colorRampPalette(c("grey85", "black")), 
                   cuts = seq(0,1,0.05)), 
  
  "generic" = new("VegQuant",
                  id = "generic",
                  name = "Generic Variable",
                  type = "unknown",
                  units = "",
                  colours = fields::tim.colors,
                  cuts = integer(0)),
  
  "lai"= new("VegQuant",
             id = "lai",
             name = "LAI",
             type = "PFT",
             units = "m^2/m^2",
             colours = lai.palette,
             cuts = seq(0,7, 0.01)),
  
  "mlai"=  new("VegQuant",
               id = "mlai",
               name = "Monthly LAI",
               type = "monthly",
               units = "m^2/m^2",
               colours = lai.palette,
               cuts = seq(0,10, 0.2)),
  
  "fpc" = new("VegQuant",
              id = "fpc",
              name = "Foliar Projective Cover",
              type = "PFT",
              units = "m^2/m^2",
              colours = veg.palette,
              cuts = seq(0,1.5, 0.02)),     
  
  "mfpc" = new("VegQuant",
               id = "mfpc",
               name = "Monthly Foliar Projective Cover",
               type = "Monthly",
               units = "m^2/m^2",
               colours = veg.palette,
               cuts = seq(0,1.5, 0.02)),
  
  "vegcover"= new("VegQuant",
                  id = "vegcover",
                  name = "Vegetation Cover",
                  type = "",
                  units = "m^2/m^2",
                  colours = veg.palette,
                  cuts = seq(0,1.0, 0.02)),
  
  "agpp" =  new("VegQuant",
                id = "agpp",
                name = "Annual GPP",
                type = "PFT",
                units = "kgC/m2/year",
                colours = fields::tim.colors,
                cuts = seq(0, 3, 0.05)),
  
  "cmass"= new("VegQuant",
               id = "cmass",
               name = "Vegetation Carbon Mass",
               type = "PFT",
               units = "kgC/m^2",
               colours = cmass.palette,
               cuts = seq(0,40,1)),
  
  "agb" = new("VegQuant",
              id = "agb",
              name = "Above Ground Biomass",
              type = "PFT",
              units = "tonnes/hectare",
              colours = cmass.palette,
              cuts = seq(0,800,10)),
  
  "cpool" =  new("VegQuant",
                 id = "cpool",
                 name = "Carbon Pool",
                 type = "pools",
                 units = "kgC/m^2",
                 colours = fields::tim.colors,
                 cuts = seq(0,70,1)),
  
  "litter_wood"= new("VegQuant",
                     id = "litter_wood",
                     name = "Wood Litter",
                     type = "PFT",
                     units = "kgC/m^2",
                     colours = fields::tim.colors,
                     cuts = seq(0,2,0.1)),
  
  "litter_leaf" =  new("VegQuant",
                       id = "litter_leaf",
                       name = "Leaf Litter",
                       type = "PFT",
                       units = "kgC/m^2",
                       colours = fields::tim.colors,
                       cuts = seq(0,1,0.002)),
  
  "litter_repr"=  new("VegQuant",
                      id = "litter_repr",
                      name = "Reproductive Litter",
                      type = "PFT",
                      units = "kgC/m^2",
                      colours = fields::tim.colors,
                      cuts = seq(0,1,0.05)),
  
  "fine_fuel" = new("VegQuant",
                    id = "fine_fuel",
                    name = "Fine Fuel",
                    type = "PFT",
                    units = "kgC/m^2",
                    colours = fields::tim.colors,
                    cuts = seq(0,1,0.05)),
  
  "mnpp" =  new("VegQuant",
                id = "mnpp",
                name = "Month NPP",
                type = "monthly",
                units = "kgC/m^2",
                colours = fields::tim.colors,
                cuts = seq(-0.1, 0.3, 0.01)),
  
  "mgpp" = new("VegQuant",
               id = "mgpp",
               name = "Monthly GPP", 
               type = "monthly",
               units = "kgC/m^2",
               colours = fields::tim.colors,
               cuts = seq(0, 0.4, 0.01)),
  
  "mnee" = new("VegQuant",
               id = "mnee",
               name = "Monthly NEE", 
               type = "monthly",
               units = "kgC/m^2",
               colours = fields::tim.colors,
               cuts = seq(-0.1, 0.2, 0.01)),
  
  "mrh" =new("VegQuant",
             id = "mrh",
             name = "Monthly Heterotrophic Respiration", 
             type = "monthly",
             units = "kgC/m^2",
             colours = fields::tim.colors,
             cuts = seq(0.0, 0.3, 0.005)),
  
  "mra" =  new("VegQuant",
               id = "mra",
               name = "Monthly Autotrophic Respiration", 
               type = "monthly",
               units = "kgC/m^2",
               colours = fields::tim.colors,
               cuts = seq(0.0, 0.3, 0.005)),
  
  "anpp" = new("VegQuant",
               id = "anpp",
               name = "Annual NPP", 
               type = "PFT",
               units = "kgC/m^2",
               colours = fields::tim.colors,
               cuts = seq(-0.5, 2, 0.1)),
  
  "cflux" = new("VegQuant",
                id = "cflux",
                name = "Carbon Flux", 
                type = "flux",
                units = "kgC/m^2/y",
                colours = fields::tim.colors,
                cuts = seq(-3, 3, 0.1)),
  
  "dens" = new("VegQuant",
               id = "dens",
               name = "PFT Density", 
               type = "PFT",
               units = "indiv/m^2",
               colours = fields::tim.colors,
               cuts = seq(0, 0.1, 0.002)),
  
  "speciesheights"= new("VegQuant",
                        id = "speciesheights",
                        name = "PFT Average Heights", 
                        type = "PFT",
                        units = "m",
                        colours = fields::tim.colors,
                        cuts = seq(0, 40, 1)),
  
  "maet"  = new("VegQuant",
                id = "maet",
                name = "Monthly Actual Evapotranspiration", 
                type = "monthly",
                units = "mm/month",
                colours = fields::tim.colors,
                cuts = seq(0, 200, 10)),
  
  "mpet" = new("VegQuant",
               id = "mpet",
               name = "Monthly Potential Evapotranspiration", 
               type = "monthly",
               units = "mm/month",
               colours = fields::tim.colors,
               cuts = seq(0, 300, 10)),
  
  "mevap" = new("VegQuant",
                id = "mevap",
                name = "Monthly Evaporation", 
                type = "monthly",
                units = "mm/month",
                colours = fields::tim.colors,
                cuts = seq(0, 100, 2)),
  
  "mrunoff" = new("VegQuant",
                  id = "mrunoff",
                  name = "Monthly Runoff", 
                  type = "monthly",
                  units = "mm/month",
                  colours = fields::tim.colors,
                  cuts = seq(0, 500, 10)),
  
  "mintercep" = new("VegQuant",
                    id = "mintercep",
                    name = "Monthly Interception", 
                    type = "monthly",
                    units = "mm/month",
                    colours = fields::tim.colors,
                    cuts = seq(0, 50, 1)),
  
  "mwcont_upper" =  new("VegQuant",
                        id = "mwcont_upper",
                        name = "Monthly Upper Soil Layer WC", 
                        type = "monthly",
                        units = "",
                        colours = reversed.tim.colors,
                        cuts = seq(0, 1, 0.02),
                        aggregate.method = "mean")
  ,
  
  "mwcont_lower" =  new("VegQuant",
                        id = "mwcont_lower",
                        name = "Monthly Lower Soil Layer", 
                        type = "monthly",
                        units = "",
                        colours = reversed.tim.colors,
                        cuts = seq(0, 1, 0.02),
                        aggregate.method = "mean"),
  
  "msnowpack" = new("VegQuant",
                    id = "msnowpack",
                    name = "Monthly Snow Pack", 
                    type = "monthly",
                    units = "mm H20",
                    colours = reversed.tim.colors,
                    cuts = seq(0, 5, 0.02)), 
  
  "firert" = new("VegQuant",
                 id = "firert",
                 name = "Fire Return Interval", 
                 type = "annual",
                 units = "years",
                 colours = fire.palette,
                 cuts = c(0,3,6,12,25,50,100,200,400,800,1000)),
  
  "fireseason" = new("VegQuant",
                     id = "fireseason",
                     name = "Fire Season Length", 
                     type = "annual",
                     units = "days",
                     colours = fire.palette,
                     cuts = seq(0, 365, 5)),
  
  "firesl" = new("VegQuant",
                 id = "firesl",
                 name = "Fire Season Length", 
                 type = "annual",
                 units = "days",
                 colours = fire.palette,
                 cuts = seq(0, 365, 5)), 
  
  "burntarea" = new("VegQuant",
                    id = "burntarea",
                    name = "Annual Fraction Burned", 
                    type = "annual",
                    units = "fraction of gridcell",
                    colours = fire.palette,
                    cuts = seq(0, 1.0, 0.01)),
  
  "burntfraction" = new("VegQuant",
                    id = "burntfraction",
                    name = "Annual Fraction Burned", 
                    type = "annual",
                    units = "fraction of gridcell",
                    colours = reversed.fire.palette,
                    cuts = seq(0, 1.0, 0.02)),
  
  "tot_runoff" = new("VegQuant",
                     id = "tot_runoff",
                     name = "Annual Total Runoff", 
                     type = "annual",
                     units = "mm/year",
                     colours = fields::tim.colors,
                     cuts = seq(0, 1000, 50)), 
  
  "bioclim" = new("VegQuant",
                  id = "bioclim",
                  name = "Bioclimatic Limit Variables",
                  type = "irregular",
                  units = "kgC/m^2",
                  colours = fields::tim.colors,
                  cuts = seq(-1, 3, 0.1)),
  
  "gdd5" = new("VegQuant",
               id = "gdd5",
               name = "Growing Degree Days (5deg C base)",
               type = "annual",
               units = "degree days",
               colours = fields::tim.colors,
               cuts = seq(0, 5000, 100)),
  
  
  #############################################################################################
  ############################# SPITFIRE QUANTITES ############################################
  #############################################################################################
  
  "mfirefrac" = new("VegQuant",
                    id = "mfirefrac",
                    name = "Monthly Burned Area Fraction", 
                    type = "monthly",
                    units = "",
                    colours = fields::tim.colors,
                    cuts = seq(0,1,0.05)),
  
  "mtau_l" =  new("VegQuant",
                  id = "mtau_l",
                  name = "Monthly Residence Time", 
                  type = "monthly",
                  units = "mins",
                  colours = fields::tim.colors,
                  cuts = seq(0,8,0.2)),
  
  "pyro_flux" = new("VegQuant",
                    id = "pyro_flux",
                    name = "Pyrogenic Emmisions", 
                    type = "irregular",
                    units = "kg species/m^2",
                    colours = fields::tim.colors),
  
  "mfireintens" = new("VegQuant",
                      id = "mfireintens",
                      name = "Monthly Fire Intensity", 
                      type = "monthly",
                      units = "kW/m^2",
                      colours = fields::tim.colors,
                      cuts = seq(0, 5000, 50)),
  
  "mlivegrass_fuel" = new("VegQuant",
                          id = "mlivegrass_fuel",
                          name = "Mean Monthly Live Grass Fuel", 
                          type = "monthly",
                          units = "kgC/m^2",
                          colours = fields::tim.colors,
                          cuts = seq(0,1,0.01)),
  
  "m1hr_fuel" = new("VegQuant",
                    id = "m1hr_fuel",
                    name = "Mean Monthly 1hr Fuel", 
                    type = "monthly",
                    units = "kgC/m^2",
                    colours = fields::tim.colors,
                    cuts = seq(0,1,0.01)),
  
  "m10hr_fuel" = new("VegQuant",
                     id = "m10hr_fuel",
                     name = "Mean Monthly 10hr Fuel", 
                     type = "monthly",
                     units = "kgC/m^2",
                     colours = fields::tim.colors,
                     cuts = seq(0,1,0.01)),
  
  "m100hr_fuel" = new("VegQuant",
                      id = "m100hr_fuel",
                      name = "Mean Monthly 100hr Fuel", 
                      type = "monthly",
                      units = "kgC/m^2",
                      colours = fields::tim.colors,
                      cuts = seq(0,1,0.01)),
  
  "m1000hr_fuel" = new("VegQuant",
                       id = "m1000hr_fuel",
                       name = "Mean Monthly 1000hr Fuel", 
                       type = "monthly",
                       units = "kgC/m^2",
                       colours = fields::tim.colors,
                       cuts = seq(0,1,0.01)),
  
  "mlivegrass_cc" = new("VegQuant",
                        id = "mlivegrass_cc",
                        name = "Mean Monthly Live Grass Combustion Completeness", 
                        type = "monthly",
                        units = "kgC/m^2",
                        colours = fields::tim.colors,
                        cuts = seq(0,1,0.01)),     
  
  "m1hr_cc"= new("VegQuant",
                 id = "m1hr_cc",
                 name = "Mean Monthly 1hr Combustion Completeness", 
                 type = "monthly",
                 units = "kgC/m^2",
                 colours = fields::tim.colors,
                 cuts = seq(0,1,0.01)),
  
  "m10hr_cc" = new("VegQuant",
                   id = "m10hr_cc",
                   name = "Mean Monthly 10hr Combustion Completeness", 
                   type = "monthly",
                   units = "kgC/m^2",
                   colours = fields::tim.colors,
                   cuts = seq(0,1,0.01)),
  
  "m100hr_cc" = new("VegQuant",
                    id ="m100hr_cc",
                    name = "Mean Monthly 100hr Combustion Completeness", 
                    type = "monthly",
                    units = "kgC/m^2",
                    colours = fields::tim.colors,
                    cuts = seq(0,1,0.01)),
  
  "m1000hr_cc" = new("VegQuant",
                     id = "m1000hr_cc",
                     name = "Mean Monthly 1000hr Combustion Completeness", 
                     type = "monthly",
                     units = "kgC/m^2",
                     colours = fields::tim.colors,
                     cuts = seq(0,1,0.01)),
  
  "afdays" = new("VegQuant",
                 id = "afdays",
                 name = "Fire Days per Year", 
                 type = "annual",
                 units = "days",
                 colours = fields::tim.colors,
                 cuts = seq(0, 366, 12)),
  
  "mavenest" = new("VegQuant",
                   id = "mavenest",
                   name = "Average Monthly Nesterov", 
                   type = "monthly",
                   units = "",
                   colours = fields::tim.colors,
                   cuts = seq(0, 100000, 5000)),
  
  "mdlm_livegrass" = new("VegQuant",
                         id = "mdlm_livegrass",
                         name = "Monthly Litter Moisture of Live Grass", 
                         type = "monthly",
                         units = "",
                         colours = fields::tim.colors,
                         cuts = seq(0, 1, 0.02)),
  
  "mdlm_deadfuel" = new("VegQuant",
                        id = "mdlm_deadfuel",
                        name = "Monthly Litter Moisture of Dead Fuel", 
                        type = "monthly",
                        units = "",
                        colours = fields::tim.colors,
                        cuts = seq(0, 1, 0.02)),
  
  "meff_wind" = new("VegQuant",
                    id = "meff_wind",
                    name = "Monthly Effective Windspeed", 
                    type = "monthly",
                    units = "m/min",
                    colours = fields::tim.colors,
                    cuts = seq(0, 100, 0.2)),
  
  "mnfdi" = new("VegQuant",
                id = "mnfdi",
                name = "Monthly Nesterov Fire Danger Index", 
                type = "monthly",
                units = "m/min",
                colours = fields::tim.colors,
                cuts = seq(0, 1, 0.02)),
  
  "mFBD" = new("VegQuant",
               id = "mFBD",
               name = "Monthly Fuel Bulk Density", 
               type = "monthly",
               units = "m^3/m^3",
               colours = fields::tim.colors,
               cuts = seq(0, 30, 1)),
  
  "mSAV" = new("VegQuant",
               id = "mSAV",
               name = "Monthly Surface Area to Volume Ratio", 
               type = "monthly",
               units = "m^2/m^3",
               colours = fields::tim.colors,
               cuts = seq(25, 100, 5)),
  
  "mMoE" = new("VegQuant",
               id = "mMoE",
               name = "Monthly Moisture of Extinction", 
               type = "monthly",
               units = "",
               colours = fields::tim.colors,
               cuts = seq(0.2, 0.4, 0.01)),
  
  "mmcont" = new("VegQuant",
                 id = "mmcont",
                 name = "Monthly Fuel Moisture Content", 
                 type = "monthly",
                 units = "",
                 colours = fields::tim.colors,
                 cuts = seq(0, 1, 0.05)),
  
  "mfire_durat" = new("VegQuant",
                      id = "mfire_durat",
                      name = "Monthly Fire Duration", 
                      type = "monthly",
                      units = "mins",
                      colours = fields::tim.colors,
                      cuts = seq(0, 250, 5)),
  
  "mscorch_height" = new("VegQuant",
                         id = "mscorch_height",
                         name = "Monthly Scorch Height", 
                         type = "monthly",
                         units = "m",
                         colours = fields::tim.colors,
                         cuts = seq(0, 30, 1)),
  
  "mros" = new("VegQuant",
               id = "mros",
               name = "Monthly Rate of Spread", 
               type = "monthly",
               units = "m/min",
               colours = fields::tim.colors,
               cuts = seq(0, 30, 1)),
  
  "mfire_size" = new("VegQuant",
                     id = "mfire_size",
                     name = "Monthly Fire Size", 
                     type = "monthly",
                     units = "ha",
                     colours = fields::tim.colors,
                     cuts = seq(0, 100, 1)),
  
  "mhuman_ign" = new("VegQuant",
                     id = "mhuman_ign",
                     name = "Monthly average of human ignition rate", 
                     type = "monthly",
                     units = "ign/day",
                     colours = fields::tim.colors,
                     cuts = seq(0, 100, 1)),
  
  "mlightning_ign" = new("VegQuant",
                         id = "mlightning_ign",
                         name = "Monthly average of lightning ignition rate", 
                         type = "monthly",
                         units = "ign/day",
                         colours = fields::tim.colors,
                         cuts = seq(0, 5, 0.1)),
  
  "mfireday_duration" = new("VegQuant",
                            id = "mfireday_duration",
                            name = "Monthly Fire Duration (Fire Days Only)", 
                            type = "monthly",
                            units = "mins",
                            colours = fields::tim.colors,
                            cuts = seq(0, 250, 5)),
  
  "mfireday_scorch_height" = new("VegQuant",
                                 id = "mfireday_scorch_height",
                                 name = "Monthly Scorch Height (Fire Days Only)", 
                                 type = "monthly",
                                 units = "m",
                                 colours = fields::tim.colors,
                                 cuts = seq(0, 30, 1)),
  
  "mfireday_intensity" = new("VegQuant",
                             id = "mfireday_intensity",
                             name = "Monthly Fire Intensity (Fire Days Only)", 
                             type = "monthly",
                             units = "kW/m",
                             colours = fields::tim.colors,
                             cuts = seq(0, 500000, 5000)),
  
  "mfireday_nesterov" =  new("VegQuant",
                             id = "mfireday_nesterov",
                             name = "Monthly Nesterov (Fire Days Only)", 
                             type = "monthly",
                             units = "",
                             colours = fields::tim.colors,
                             cuts = seq(0, 5000000, 5000)),
  
  "mfireday_residence_time" = new("VegQuant",
                                  id = "mfireday_residence_time",
                                  name = "Monthly Residence Time (Fire Days Only)", 
                                  type = "monthly",
                                  units = "min",
                                  colours = fields::tim.colors,
                                  cuts = seq(0, 10, 0.1)),
  
  "allocation_fails" = new("VegQuant",
                           id = "allocation_fails",
                           name = "Monthly Allocation Fails", 
                           type = "annual",
                           units = "days",
                           colours = fields::tim.colors,
                           cuts = seq(0,31,1)),
  
  "allocation_iters" = new("VegQuant",
                           id = "allocation_iters",
                           name = "Monthly Iteration To Allocation Fire", 
                           type = "annual",
                           units = "days",
                           colours = fields::tim.colors,
                           cuts = seq(0,20,1)),
  
  "mfuel" = new("VegQuant",
                id = "mfuel",
                name = "Monthly Fuel", 
                type = "monthly",
                units = "kgC/m^2",
                colours = fields::tim.colors,
                cuts = seq(0,1.0,0.1),
                aggregate.method = "mean"),
  
  "mfinefuel" = new("VegQuant",
                    id = "mfinefuel",
                    name = "Monthly Fine Fuel", 
                    type = "monthly",
                    units = "kgC/m^2",
                    colours = fields::tim.colors,
                    cuts = seq(0,1.0,0.1),
                    aggregate.method = "mean"),
  
  "mfiredays" = new("VegQuant",
                    id = "mfiredays",
                    name = "Monthly sum of daily fire probabilites", 
                    type = "monthly",
                    units = "days",
                    colours = fields::tim.colors,
                    cuts = seq(0,31,1),
                    aggregate.method = "sum"),
  
  "mfiredays_fine" = new("VegQuant",
                         id = "mfiredaysfine",
                         name = "Monthly sum of daily fire probabilites (based on fine fuel threshold)", 
                         type = "monthly",
                         units = "days",
                         colours = fields::tim.colors,
                         cuts = seq(0,31,1),
                         aggregate.method = "sum")#,
  
  
  
)




