#!/usr/bin/Rscript

#' Retrieve a Quantity from the standard list.
#'
#' Function to get an Quantity based on an ID string *and* the scope (i.e. a particular model or the 'Standard' properties) from the standard \code{dgvm.quantities} list
#' 
#' @param quant.id String holding the id of the \code{Quantity} you want
#' @param model.str String holding the name of the model or "Standard"
#' @author Matthew Forrest \email{matthew.forrest@@senckenberg.de}
#' @return A \code{Quantity} object if it finds the right one.  Otherwise the code halts.
lookupQuantity <- function(quant.id, model.str = "Standard"){
  
  for(quant in dgvm.quantities){
    
    if(quant.id == quant@id & model.str %in% quant@model) return(quant)
    
  }
  
  if(substr(quant.id, nchar(quant.id) - nchar("_std") +1, nchar(quant.id)) != "_std") warning(paste0("Can find a quantity with id = ", quant.id, " and model = ", model.str, " in dgvm.quantities, now searching only on the quant.id."))
  
  for(quant in dgvm.quantities){
    
    if(quant.id == quant@id) return(quant)
    
  }
  
  stop(paste0("Can find a quantity with id = ", quant.id, " anywhere in dgvm.quantities"))
  
}



#' @title dummy text
#' 
#' @description A global scope list of all many quantites for many models defined by the \code{dgvm.quantities} list below.
#' Once the package is loaded this is just a standard R list so can be modified and extended as you wish.  It can be conveniently accesed by the \code{lookupQuantity()} function.
#' 
#' @details These quantities have sensible colour schemes, long names and cut ranges for standard global runs,
#' but they will likely need to be modified and new ones aded for a specific analysis.
#' 
#' @format \code{dgvm.quantities} is list of \code{Quantity} objects that store meta-data for common output variables from supported models as well as some standard quantities
#' which should be derivable from all model output.
#' @rdname Quantity-class
#' @keywords datasets
#' @importFrom fields tim.colors  
#' @seealso \code{lookupQuantity}
dgvm.quantities <- list(
  
  ######################################################################
  ########## STANDARD (CROSS-MODEL) QUANTITIES  ########################
  #####################################################################
  
  new("Quantity",
      id = "fraction",
      type = "unknown",
      name = "Fraction",
      units = "",
      colours = grDevices::colorRampPalette(c("grey85", "black")), 
      model = "Standard"), 
 
  new("Quantity",
      id = "vegcover_std",
      type = "",
      name = "Areal Cover",
      units = "%",
      colours = veg.palette, 
      model = "Standard"), 
  
  new("Quantity",
      id = "vegC_std",
      name = "Vegetation Carbon Mass",
      type = "PFT",
      units = "kgC/m^2",
      colours = cmass.palette,
      model = c("Standard")),
  
  new("Quantity",
      id = "LAI_std",
      name = "LAI",
      type = "PFT",
      units = "m^2/m^2",
      colours = lai.palette,
      model = c("Standard")),
  
  new("Quantity",
      id = "mGPP_std",
      name = "Monthly GPP",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("Standard")),
  
  new("Quantity",
      id = "aGPP_std",
      name = "Annual GPP",
      type = "PFT",
      units = "kgC/m^2/year",
      colours = fields::tim.colors,
      model = c("Standard")),
  
  new("Quantity",
      id = "aNPP_std",
      name = "Annual NPP",
      type = "PFT",
      units = "kgC/m^2/year",
      colours = fields::tim.colors,
      model = c("Standard")),
  
  new("Quantity",
      id = "canopyheight_std",
      name = "Canopy Height",
      type = "-",
      units = "m",
      colours = fields::tim.colors,
      model = c("Standard")),
  
  new("Quantity",
      id = "burntfraction_std",
      name = "Annual Fraction Burned",
      type = "annual",
      units = "fraction of gridcell",
      colours = reversed.fire.palette,
      model = c("Standard")),
  
  new("Quantity",
      id = "FPAR_std",
      name = "Fraction absorbed of Photosynthetically Active Radiation",
      type = "annual",
      units = "fraction",
      colours = veg.palette,
      model = c("Standard")),
  
  
  ### NITROGEN QUANTITES
  
  
  ######################################################################
  ########## FIREMIP QUANTITIES  ######################################
  ######################################################################  
  
  new("Quantity",
      id = "landCoverFrac",
      type = "",
      name = "Areal Cover",
      units = "%",
      colours = veg.palette, 
      model = "FireMIP",
      aggregate.method = "sum"), 
  
  new("Quantity",
      id = "lai",
      type = "",
      name = "Leaf Area Index",
      units = "-",
      colours = viridis, 
      model = "FireMIP"), 
  
  new("Quantity",
      id = "theightpft",
      type = "",
      name = "Tree Height",
      units = "m",
      colours = veg.palette, 
      model = "FireMIP"), 
  
  new("Quantity",
      id = "gpp",
      type = "monthly",
      name = "Gross Primary Productivity",
      units = "-",
      colours = veg.palette, 
      model = "FireMIP"), 
  
  
  ######################################################################
  ########## LPJ-GUESS QUANTITIES  #####################################
  ######################################################################  
  
  new("Quantity",
      id = "lai",
      name = "LAI",
      type = "PFT",
      units = "m^2/m^2",
      colours = lai.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE", "aDGVM")),
  
  new("Quantity",
      id = "mlai",
      name = "Monthly LAI",
      type = "monthly",
      units = "m^2/m^2",
      colours = lai.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "fpc",
      name = "Foliar Projective Cover",
      type = "PFT",
      units = "m^2/m^2",
      colours = veg.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfpc",
      name = "Monthly Foliar Projective Cover",
      type = "Monthly",
      units = "m^2/m^2",
      colours = veg.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "vegcover",
      name = "Vegetation Cover",
      type = "",
      units = "m^2/m^2",
      colours = veg.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "agpp",
      name = "Annual GPP",
      type = "PFT",
      units = "kgC/m2/year",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "cmass",
      name = "Vegetation Carbon Mass",
      type = "PFT",
      units = "kgC/m^2",
      colours = cmass.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "clitter",
      name = "Litter Carbon Mass",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "agb",
      name = "Above Ground Biomass",
      type = "PFT",
      units = "tonnes/hectare",
      colours = cmass.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "cpool",
      name = "Carbon",
      type = "pools",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "litter_wood",
      name = "Wood Litter",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "litter_leaf",
      name = "Leaf Litter",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "litter_repr",
      name = "Reproductive Litter",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "fine_fuel",
      name = "Fine Fuel",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mnpp",
      name = "NPP",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mgpp",
      name = "GPP",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mnee",
      name = "Monthly NEE",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mrh",
      name = "Monthly Heterotrophic Respiration",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mra",
      name = "Monthly Autotrophic Respiration",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "anpp",
      name = "Annual NPP",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "cflux",
      name = "Carbon Flux",
      type = "flux",
      units = "kgC/m^2/y",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "dens",
      name = "PFT Density",
      type = "PFT",
      units = "indiv/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "speciesheights",
      name = "PFT Average Heights",
      type = "PFT",
      units = "m",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "maet",
      name = "Monthly Actual Evapotranspiration",
      type = "monthly",
      units = "mm/month",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mpet",
      name = "Monthly Potential Evapotranspiration",
      type = "monthly",
      units = "mm/month",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mevap",
      name = "Monthly Evaporation",
      type = "monthly",
      units = "mm/month",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mrunoff",
      name = "Monthly Runoff",
      type = "monthly",
      units = "mm/month",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mintercep",
      name = "Monthly Interception",
      type = "monthly",
      units = "mm/month",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mwcont_upper",
      name = "Monthly Upper Soil Layer",
      type = "monthly",
      units = "fraction",
      colours = reversed.tim.colors,
      aggregate.method = "mean",
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mwcont_lower",
      name = "Monthly Lower Soil Layer",
      type = "monthly",
      units = "fraction",
      colours = reversed.tim.colors,
      aggregate.method = "mean",
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "msnowpack",
      name = "Monthly Snow Pack",
      type = "monthly",
      units = "mm H20",
      colours = reversed.tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "firert",
      name = "Fire Return Interval",
      type = "annual",
      units = "years",
      colours = fire.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "fireseason",
      name = "Fire Season Length",
      type = "annual",
      units = "days",
      colours = fire.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "firesl",
      name = "Fire Season Length",
      type = "annual",
      units = "days",
      colours = fire.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "burntarea", 
      name = "Annual Fraction Burned",
      type = "annual",
      units = "fraction of gridcell",
      colours = fire.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "burntfraction",
      name = "Annual Fraction Burned",
      type = "annual",
      units = "fraction of gridcell",
      colours = reversed.fire.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "tot_runoff",
      name = "Runoff",
      type = "annual",
      units = "mm/year",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "vmaxnlim",
      name = "Nitrogen Limitation to Vmax",
      type = "PFT",
      units = "fraction",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE"),
      aggregate.method = "mean"),
  
  new("Quantity",
      id = "bioclim",
      name = "Bioclimatic Limit Variables",
      type = "irregular",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "gdd5",
      name = "Growing Degree Days (5deg C base)",
      type = "annual",
      units = "degree days",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  
  new("Quantity",
      id = "aleafshed",
      name = "Number times leafs shed per year",
      type = "PFT",
      units = "",
      colours = fields::tim.colors,
      aggregate.method = "mean",
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "cton_leaf",
      name = "C:N leaf",
      type = "PFT",
      units = "ckgC/kgN",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "nmass",
      name = "Vegetation Nitrogen Mass",
      type = "PFT",
      units = "gN/m^2",
      colours = cmass.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "npool",
      name = "Nitrogen",
      type = "pools",
      units = "kgN/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "nuptake",
      name = "Nitrogen Uptake",
      type = "PFT",
      units = "kgN/ha",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "nsources",
      name = "Nitrogen Source",
      type = "annual",
      units = "gN/ha",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "nflux",
      name = "Nitrogen Flux",
      type = "annual",
      units = "kgN/ha",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "nflux",
      name = "Nitrogen Flux",
      type = "annual",
      units = "kgN/ha",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "nlitter",
      name = "Litter Nitrogen Mass",
      type = "PFT",
      units = "kgN/ha",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
 
  
  new("Quantity",
      id = "mprec",
      name = "Monthly Precipitation",
      type = "monthly",
      units = "mm",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
     id = "mtemp",
     name = "Mean Monthly Temperature",
     type = "monthly",
     units = "deg C",
     colours = fields::tim.colors,
     model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mwmass_stem",
      name = "Water Stored in Stem",
      type = "monthly",
      units = "kgH20/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mwmass_leaf",
      name = "Water Stored in Leaves",
      type = "monthly",
      units = "kgH20/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  
  
  #############################################################################################
  ############################# LPJ-GUESS-SPITFIRE QUANTITIES #################################
  #############################################################################################
  
  new("Quantity",
      id = "mfirefrac",
      name = "Monthly Burned Area Fraction",
      type = "monthly",
      units = "",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mtau_l",
      name = "Monthly Residence Time",
      type = "monthly",
      units = "mins",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "pyro_flux",
      name = "Pyrogenic Emmisions",
      type = "irregular",
      units = "kg species/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireintens",
      name = "Monthly Fire Intensity",
      type = "monthly",
      units = "kW/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mlivegrass_fuel",
      name = "Mean Monthly Live Grass Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1hr_fuel",
      name = "Mean Monthly 1hr Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m10hr_fuel",
      name = "Mean Monthly 10hr Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m100hr_fuel",
      name = "Mean Monthly 100hr Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1000hr_fuel",
      name = "Mean Monthly 1000hr Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mlivegrass_cc",
      name = "Mean Monthly Live Grass Combustion Completeness",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1hr_cc",
      name = "Mean Monthly 1hr Combustion Completeness",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m10hr_cc",
      name = "Mean Monthly 10hr Combustion Completeness",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id ="m100hr_cc",
      name = "Mean Monthly 100hr Combustion Completeness",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1000hr_cc",
      name = "Mean Monthly 1000hr Combustion Completeness",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "afdays",
      name = "Fire Days per Year",
      type = "annual",
      units = "days",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mavenest",
      name = "Average Monthly Nesterov",
      type = "monthly",
      units = "",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mdlm_livegrass",
      name = "Monthly Litter Moisture of Live Grass",
      type = "monthly",
      units = "",
      colours = reversed.tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mdlm_deadfuel",
      name = "Monthly Litter Moisture of Dead Fuel",
      type = "monthly",
      units = "",
      colours = reversed.tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "meff_wind",
      name = "Monthly Effective Windspeed",
      type = "monthly",
      units = "m/min",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mnfdi",
      name = "Monthly Nesterov Fire Danger Index",
      type = "monthly",
      units = "m/min",
      colours = fields::tim.colors,
      aggregate.method = "mean",
      model = c("LPJ-GUESS-SPITFIRE")),
  
  
  new("Quantity",
      id = "mFBD",
      name = "Monthly Fuel Bulk Density",
      type = "monthly",
      units = "m^3/m^3",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mSAV",
      name = "Monthly Surface Area to Volume Ratio",
      type = "monthly",
      units = "m^2/m^3",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mMoE",
      name = "Monthly Moisture of Extinction",
      type = "monthly",
      units = "",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mmcont",
      name = "Monthly Fuel Moisture Content",
      type = "monthly",
      units = "",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfire_durat",
      name = "Monthly Fire Duration",
      type = "monthly",
      units = "mins",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mscorch_height",
      name = "Monthly Scorch Height",
      type = "monthly",
      units = "m",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mRoS",
      name = "Monthly Rate of Spread",
      type = "monthly",
      units = "m/min",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfire_size",
      name = "Monthly Fire Size",
      type = "monthly",
      units = "ha",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mhuman_ign",
      name = "Monthly average of human ignition rate",
      type = "monthly",
      units = "ign/day",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mlightning_ign",
      name = "Monthly average of lightning ignition rate",
      type = "monthly",
      units = "ign/day",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_duration",
      name = "Monthly Fire Duration (Fire Days Only)",
      type = "monthly",
      units = "mins",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_scorch_height",
      name = "Monthly Scorch Height (Fire Days Only)",
      type = "monthly",
      units = "m",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_intensity",
      name = "Monthly Fire Intensity (Fire Days Only)",
      type = "monthly",
      units = "kW/m",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_nesterov",
      name = "Monthly Nesterov (Fire Days Only)",
      type = "monthly",
      units = "",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_residence_time",
      name = "Monthly Residence Time (Fire Days Only)",
      type = "monthly",
      units = "min",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "allocation_fails",
      name = "Monthly Allocation Fails",
      type = "annual",
      units = "days",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
                           id = "allocation_iters",
                           name = "Monthly Iteration To Allocation Fire",
                           type = "annual",
                           units = "days",
                           colours = fields::tim.colors,
                           model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
                id = "mfuel",
                name = "Monthly Fuel",
                type = "monthly",
                units = "kgC/m^2",
                colours = fields::tim.colors,
                aggregate.method = "mean",
                model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
                    id = "mfinefuel",
                    name = "Monthly Fine Fuel",
                    type = "monthly",
                    units = "kgC/m^2",
                    colours = fields::tim.colors,
                    aggregate.method = "mean",
                    model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
                    id = "mleaffuel",
                    name = "Monthly Leaf Fuel",
                    type = "monthly",
                    units = "kgC/m^2",
                    colours = fields::tim.colors,
                    aggregate.method = "mean",
                    model = c("LPJ-GUESS-SPITFIRE")),
  
  
  new("Quantity",
                    id = "mfiredays",
                    name = "Monthly sum of daily fire probabilites",
                    type = "monthly",
                    units = "days",
                    colours = fields::tim.colors,
                    aggregate.method = "sum",
                    model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
                         id = "mfiredaysfine",
                         name = "Monthly sum of daily fire probabilites (based on fine fuel threshold)",
                         type = "monthly",
                         units = "days",
                         colours = fields::tim.colors,
                         aggregate.method = "sum",
                         model = c("LPJ-GUESS-SPITFIRE")),
  
  #############################################################################################
  ################################### aDGVM QUANTITIES ########################################
  #############################################################################################
  
  
  new("Quantity",
      id = "agb",
      name = "Above Ground Biomass",
      type = "PFT",
      units = "kgC/m^2",
      colours = cmass.palette,
      aggregate.method = "sum",
      model = c("aDGVM")),
  
  new("Quantity",
      id = "meanheight",
      name = "Mean Canopy Height",
      type = "PFT",
      units = "m",
      colours = fields::tim.colors,
      aggregate.method = "mean",
      model = c("aDGVM")),

  new("Quantity",
      id = "nind",
      name = "Number of individuals",
      type = "PFT",
      units = "plants",
      colours = cmass.palette,
      aggregate.method = "sum",
      model = c("aDGVM"))
  
 
)




