#!/usr/bin/Rscript

#' Retrieve a Quantity from the standard list.
#'
#' Function to get an Quantity based on an ID string *and* the scope (i.e. a particular model or the 'Standard' properties) from the standard \code{dgvm.quantities} list
#' 
#' @param quant.id String holding the id of the \code{Quantity} you want
#' @param format.str String holding the name of the model or "Standard"
#' @param verbose Logical, if TRUE (default) give some extra information
#' @author Matthew Forrest \email{matthew.forrest@@senckenberg.de}
#' @return A \code{Quantity} object if it finds the right one.  Otherwise the code halts.
lookupQuantity <- function(quant.id, format.str = "Standard", verbose = TRUE){
  
  # this code will make the function first check for a user-defined dgvm.quantities list
  local.dgvm.quantities <- get('dgvm.quantities', envir=.GlobalEnv)
  
  # First look for the exact quant.id model combination
  for(quant in local.dgvm.quantities){
    if(quant.id == quant@id & format.str %in% quant@model) return(quant)
  }

  # then look for a match on the name only
  for(quant in local.dgvm.quantities){
    if(quant.id == quant@id) {
      if(substr(quant.id, nchar(quant.id) - nchar("_std") +1, nchar(quant.id)) != "_std" && verbose) {
        warning(paste0("Didn't find a quantity with id = ", quant.id, " and format= ", format.str, " in dgvm.quantities, returning one with format = ", quant@format ,"."))
      }
      return(quant)
    }
  }
  
  # this code will make the function first check for a user-defined dgvm.quantities list
  local.supported.biome.schemes <- get('supported.biome.schemes', envir=.GlobalEnv)
  
  for(biome.scheme in local.supported.biome.schemes){
    if(as(object = biome.scheme, Class = "Quantity")@id == quant.id) return(as(object = biome.scheme, Class = "Quantity"))
  }
  
  # fail because can't find the quantity
  stop(paste0("Can't find a quantity with id = ", quant.id, " anywhere in dgvm.quantities or in the supported biome schemes (either the version in the package, or a user-extended version)"))
  
}



#' @title dummy text
#' 
#' @description A global scope list of all many quantites for many models defined by the \code{dgvm.quantities} list below.
#' Once the package is loaded this is just a standard R list so can be modified and extended as you wish.  It can be conveniently accesed by the \code{lookupQuantity()} function.
#' 
#' @details These quantities have sensible colour schemes, long names and cut ranges for standard global runs,
#' but they will likely need to be modified and new ones aded for a specific analysis.
#' 
#' @format \code{dgvm.quantities} is list of \code{Quantity} objects that store meta-data for common output variables from supported models as well as some standard quantities
#' which should be derivable from all model output.
#' @rdname Quantity-class
#' @keywords datasets
#' @importFrom fields tim.colors  
#' @seealso \code{lookupQuantity}
dgvm.quantities <- list(
  
  ######################################################################
  ########## STANDARD (CROSS-FORMAT) QUANTITIES  ########################
  #####################################################################
  
  new("Quantity",
      id = "fraction",
      type = "unknown",
      name = "Fraction",
      units = "",
      colours = grDevices::colorRampPalette(c("grey85", "black")), 
      model = c("Standard","DGVMData"),
      cf.name = "area_fraction"), 
  
  new("Quantity",
      id = "vegcover_std",
      type = "",
      name = "Area Fraction",
      units = "%",
      colours = veg.palette, 
      model = c("Standard", "DGVMData"),
      cf.name = "area_fraction_percent"), 
  
  new("Quantity",
      id = "vegC_std",
      name = "Vegetation Carbon Mass",
      type = "PFT",
      units = "kg m-2",
      colours = reversed.viridis,
      model = c("Standard", "DGVMData"),
      cf.name = "vegetation_carbon_content"),
  
  new("Quantity",
      id = "LAI_std",
      name = "LAI",
      type = "PFT",
      units = "1",
      colours = viridis::viridis,
      model = c("Standard"),
      cf.name = "leaf_area_index"),
  
  new("Quantity",
      id = "mGPP_std",
      name = "Monthly GPP",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("Standard")),
  
  new("Quantity",
      id = "aGPP_std",
      name = "Annual GPP",
      type = "PFT",
      units = "kgC m-2 year-1",
      colours = fields::tim.colors,
      model = c("Standard", "DGVMData"),
      cf.name = "annual_gross_primary_productivity_of_biomass_expressed_as_carbon"),
  
  new("Quantity",
      id = "aNPP_std",
      name = "Annual NPP",
      type = "PFT",
      units = "kgC/m^2/year",
      colours = fields::tim.colors,
      model = c("Standard")),
  
  new("Quantity",
      id = "canopyheight_std",
      name = "Canopy Height",
      type = "-",
      units = "m",
      colours = reversed.magma,
      model = c("Standard", "DGVMData"),
      cf.name = "canopy_height"),
  
  new("Quantity",
      id = "burntfraction_std",
      name = "Annual Fraction Burned",
      type = "annual",
      units = "fraction of gridcell",
      colours = reversed.fire.palette,
      model = c("Standard", "DGVMData"),
      cf.name = "burned_area_fraction"),
  
  new("Quantity",
      id = "FPAR_std",
      name = "Fraction absorbed of Photosynthetically Active Radiation",
      type = "annual",
      units = "fraction",
      colours = veg.palette,
      model = c("Standard", "DGVMData"),
      cf.name = "fraction_absorbed_of_photosynthetically_active_radiation"),
  
  new("Quantity",
      id = "aNEE_std",
      name = "Annual land sink (NEE)",
      type = "annual",
      units = "GtC/year",
      colours = veg.palette,
      model = c("Standard")),
  
  
  ### NITROGEN QUANTITES
  
  
  ######################################################################
  ########## FIREMIP QUANTITIES  ######################################
  ######################################################################  
  
  
  #### BURNT AREA AND EMISSIONS
  
  new("Quantity",
      id = "fFirePFT",
      type = "",
      name = "C emitted from fire (per PFT)",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "C emitted from fire (per PFT)"),

  new("Quantity",
      id = "fFire",
      type = "",
      name = "C emitted from fire",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "CO2 emitted from fire"),

  new("Quantity",
      id = "coFire",
      type = "",
      name = "CO emitted from fire",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "CO emitted from fire"),

  new("Quantity",
      id = "burntArea",
      type = "",
      name = "Burnt Area Fraction (per PFT)",
      units = "%",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Burnt Area Fraction (per PFT)"),

  new("Quantity",
      id = "BA",
      type = "",
      name = "Burnt Area Fraction (monthly)",
      units = "%",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Burnt Area Fraction (monthly)"),
  
  new("Quantity",
      id = "fFirepft",
      type = "",
      name = "C emitted from fire (per PFT)",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "C emitted from fire (per PFT)"),
  


  ### FUEL LOADS

  new("Quantity",
      id = "cFuelLiveGrass",
      type = "",
      name = "Carbon in live grass fuel",
      units = "kg C m-2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Carbon in live grass fuel"),

  new("Quantity",
      id = "cFuel1hr",
      type = "",
      name = "Carbon in 1hr fuel",
      units = "kg C m-2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Carbon in 1hr fuel"),

  new("Quantity",
      id = "cFuel10hr",
      type = "",
      name = "Carbon in 10hr fuel",
      units = "kg C m-2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Carbon in 10hr fuel"),

  new("Quantity",
      id = "cFuel100hr",
      type = "",
      name = "Carbon in 100hr fuel",
      units = "kg C m-2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Carbon in 100hr fuel"),

  new("Quantity",
      id = "cFuel1000hr",
      type = "",
      name = "Carbon in 1000hr fuel",
      units = "kg C m-2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Carbon in 1000hr fuel"),


  ### COMBUSION COMPLETENESS

  new("Quantity",
      id = "ccFuelLiveGrass",
      type = "",
      name = "Combusion Completeness in live grass fuel",
      units = "%",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Combusion Completeness live grass fuel"),

  new("Quantity",
      id = "ccFuel1hr",
      type = "",
      name = "Combustion Completeness in 1hr fuel",
      units = "%",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Combustion Completenessin 1hr fuel"),

  new("Quantity",
      id = "ccFuel10hr",
      type = "",
      name = "Combustion Completenessin 10hr fuel",
      units = "%",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Combustion Completeness in 10hr fuel"),

  new("Quantity",
      id = "ccFuel100hr",
      type = "",
      name = "Combustion Completenessin 100hr fuel",
      units = "%",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Combustion Completeness in 100hr fuel"),

  new("Quantity",
      id = "ccFuel1000hr",
      type = "",
      name = "Combustion Completenessin 1000hr fuel",
      units = "%",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Combustion Completeness in 1000hr fuel"),


  ### FUEL MOISTURE

  new("Quantity",
      id = "mFuelDead",
      type = "",
      name = "Fuel moisture of dead fuel",
      units = "",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Fuel moisture of dead fuel"),

  new("Quantity",
      id = "mFuelLiveGrass",
      type = "",
      name = "Fuel moisture of live grass fuel",
      units = "",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Fuel moisture of live grass fuel"),


  ### FIRE PROPERTIES AND MORTALITY

  new("Quantity",
      id = "intensFire",
      type = "",
      name = "Fireline intensity",
      units = "kW m-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Fireline intensity"),

  new("Quantity",
      id = "nrfire",
      type = "",
      name = "Number of fires",
      units = "nr m-2 month-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Number of fires"),

  new("Quantity",
      id = "meanFire",
      type = "",
      name = "Mean fire size",
      units = "m2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Mean fire size"),

  new("Quantity",
      id = "cMortality",
      type = "",
      name = "Number of individuals killed",
      units = "indiv m-2 month-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Number of individuals killed"),


  ### HYDROLOGICAL VARIABLES

  new("Quantity",
      id = "mrro",
      type = "",
      name = "Total Runoff",
      units = "kg m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Total Runoff"),

  new("Quantity",
      id = "evapotrans",
      type = "",
      name = "Total Evapo-Transpiration",
      units = "kg m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Total Evapo-Transpiration"),

  new("Quantity",
      id = "mrso",
      type = "",
      name = "Total Soil Moisture Content",
      units = "kg m-2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Total Soil Moisture Content"),

  new("Quantity",
      id = "evspsblveg",
      type = "",
      name = "Evaporation from Canopy",
      units = "kg m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Evaporation from Canopy"),

  new("Quantity",
      id = "evspsblsoi",
      type = "",
      name = "Evaporation from Soil",
      units = "kg m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Evaporation from Soil"),

  new("Quantity",
      id = "tran",
      type = "",
      name = "Transpiration",
      units = "kg m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Transpiration"),



  ### FLUXES

  new("Quantity",
      id = "gpp",
      type = "",
      name = "Gross Primary Production",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Gross Primary Production"),

  new("Quantity",
      id = "npp",
      type = "",
      name = "Net Primary Production",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Net Primary Production"),

  new("Quantity",
      id = "nbp",
      type = "",
      name = "Net Biospheric Production",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Net Biospheric Production"),

  new("Quantity",
      id = "ra",
      type = "",
      name = "Autotrophic (Plant) Respiration",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Autotrophic (Plant) Respiration"),

  new("Quantity",
      id = "rh",
      type = "",
      name = "Heterotrophic Respiration",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Heterotrophic Respiration"),

  new("Quantity",
      id = "gpppft",
      type = "",
      name = "Vegtype level GPP",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Vegtype level GPP"),

  new("Quantity",
      id = "npppft",
      type = "",
      name = "Vegtype level NPP",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Vegtype level NPP"),

  new("Quantity",
      id = "fLuc",
      type = "",
      name = "CO2 Flux to Atmosphere from Land Use Change",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "CO2 Flux to Atmosphere from Land Use Change"),


  # POOLS

  new("Quantity",
      id = "cVegpft",
      type = "",
      name = "Vegtype level Carbon in Vegetation",
      units = "kg C m-2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Vegtype level Carbon in Vegetation"),

  new("Quantity",
      id = "cVeg",
      type = "",
      name = "Carbon in Vegetation",
      units = "kg C m-2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Carbon in Vegetation"),

  new("Quantity",
      id = "cLitter",
      type = "",
      name = "Carbon in Above-ground Litter Pool",
      units = "kg C m-2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Carbon in Above-ground Litter Pool"),

  new("Quantity",
      id = "cSoil",
      type = "",
      name = "Carbon in Soil (including below-ground litter)",
      units = "kg C m-2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Carbon in Soil (including below-ground litter)"),


  ###  STRUCTURE

  new("Quantity",
      id = "landCoverFrac",
      type = "",
      name = "Fractional Land Cover of PFT",
      units = "",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Fractional Land Cover of PFT"),

  new("Quantity",
      id = "lai",
      type = "",
      name = "Leaf Area Index",
      units = "",
      colours = reversed.viridis,
      model = "FireMIP",
      cf.name = "Leaf Area Index"),

  new("Quantity",
      id = "theightpft",
      type = "",
      name = "Vegtype level tree heights",
      units = "m",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Vegtype level tree heights"),
  
  ### LAND USE
  
  new("Quantity",
      id = "cProduct",
      type = "",
      name = "Carbon in Products of Land Use Change",
      units = "kg C m-2",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "Carbon in Products of Land Use Change"),
  
  new("Quantity",
      id = "fLuc",
      type = "",
      name = "CO2 Flux to Atmosphere from Land Use Change",
      units = "kg C m-2 s-1",
      colours = reversed.viridis,
      model = c("FireMIP", "LPJ-GUESS-SPITFIRE"),
      cf.name = "CO2 Flux to Atmosphere from Land Use Change"),
  
  
  
  ######################################################################
  ########## LPJ-GUESS QUANTITIES  #####################################
  ######################################################################  
  
  new("Quantity",
      id = "lai",
      name = "LAI",
      type = "PFT",
      units = "m^2/m^2",
      colours = reversed.viridis,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE", "aDGVM"),
      cf.name = "leaf_area_index"),
  
  new("Quantity",
      id = "mlai",
      name = "Monthly LAI",
      type = "monthly",
      units = "m^2/m^2",
      colours = viridis::viridis,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE"),
      cf.name = "leaf_area_index"),
  
  new("Quantity",
      id = "fpc",
      name = "Foliar Projective Cover",
      type = "PFT",
      units = "m^2/m^2",
      colours = veg.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfpc",
      name = "Monthly Foliar Projective Cover",
      type = "Monthly",
      units = "m^2/m^2",
      colours = veg.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "vegcover",
      name = "Vegetation Cover",
      type = "",
      units = "m^2/m^2",
      colours = veg.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "agpp",
      name = "Annual GPP",
      type = "PFT",
      units = "kgC/m2/year",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "cmass",
      name = "Vegetation Carbon Mass",
      type = "PFT",
      units = "kgC/m^2",
      colours = viridis::viridis,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "clitter",
      name = "Litter Carbon Mass",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "agb",
      name = "Above Ground Biomass",
      type = "PFT",
      units = "tonnes/hectare",
      colours = viridis::viridis,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "cpool",
      name = "Carbon",
      type = "pools",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "litter_wood",
      name = "Wood Litter",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "litter_leaf",
      name = "Leaf Litter",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "litter_repr",
      name = "Reproductive Litter",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "fine_fuel",
      name = "Fine Fuel",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mnpp",
      name = "NPP",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mgpp",
      name = "GPP",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mnee",
      name = "Monthly NEE",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mrh",
      name = "Monthly Heterotrophic Respiration",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mra",
      name = "Monthly Autotrophic Respiration",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "anpp",
      name = "Annual NPP",
      type = "PFT",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "cflux",
      name = "Carbon Flux",
      type = "flux",
      units = "kgC/m^2/y",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "dens",
      name = "PFT Density",
      type = "PFT",
      units = "indiv/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "speciesheights",
      name = "PFT Average Heights",
      type = "PFT",
      units = "m",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "canopyheight",
      name = "Canopy Height",
      type = "-",
      units = "m",
      colours = reversed.magma,
      model = c("LPJ-GUESS"),
      cf.name = "canopy_height"),
  
  new("Quantity",
      id = "doc",
      name = "Dissolved Organic Carbon (?)",
      type = "-",
      units = "kgC/m^2/year",
      colours = reversed.magma,
      model = c("LPJ-GUESS"),
      cf.name = "canopy_height"),
  
  new("Quantity",
      id = "maet",
      name = "Monthly Actual Evapotranspiration",
      type = "monthly",
      units = "mm/month",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mpet",
      name = "Monthly Potential Evapotranspiration",
      type = "monthly",
      units = "mm/month",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mevap",
      name = "Monthly Evaporation",
      type = "monthly",
      units = "mm/month",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mrunoff",
      name = "Monthly Runoff",
      type = "monthly",
      units = "mm/month",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mintercep",
      name = "Monthly Interception",
      type = "monthly",
      units = "mm/month",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mwcont_upper",
      name = "Monthly Upper Soil Layer",
      type = "monthly",
      units = "fraction",
      colours = reversed.tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mwcont_lower",
      name = "Monthly Lower Soil Layer",
      type = "monthly",
      units = "fraction",
      colours = reversed.tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "msnowpack",
      name = "Monthly Snow Pack",
      type = "monthly",
      units = "mm H20",
      colours = reversed.tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
    new("Quantity",
      id = "aaet",
      name = "Annual Actual Evapotranspiration",
      type = "annual",
      units = "mm/year",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "aiso",
      name = "Annual Isoprene Emissions",
      type = "annual",
      units = "kg/year",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  
  new("Quantity",
      id = "miso",
      name = "Monthly Isoprene Emissions",
      type = "monthly",
      units = "kg/month",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "amon",
      name = "Annual Monoterpene Emissions",
      type = "annual",
      units = "kg/year",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mmon",
      name = "Monthly Monoterpene Emissions",
      type = "monthly",
      units = "kg/year",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "firert",
      name = "Fire Return Interval",
      type = "annual",
      units = "years",
      colours = fire.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "fireseason",
      name = "Fire Season Length",
      type = "annual",
      units = "days",
      colours = fire.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "firesl",
      name = "Fire Season Length",
      type = "annual",
      units = "days",
      colours = fire.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "burntarea", 
      name = "Annual Fraction Burned",
      type = "annual",
      units = "fraction of gridcell",
      colours = fire.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "burntfraction",
      name = "Annual Fraction Burned",
      type = "annual",
      units = "fraction of gridcell",
      colours = reversed.fire.palette,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE"),
      cf.name = "burned_area_fraction"),
  
  new("Quantity",
      id = "tot_runoff",
      name = "Runoff",
      type = "annual",
      units = "mm/year",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "vmaxnlim",
      name = "Nitrogen Limitation to Vmax",
      type = "PFT",
      units = "fraction",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "bioclim",
      name = "Bioclimatic Limit Variables",
      type = "irregular",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "gdd5",
      name = "Growing Degree Days (5deg C base)",
      type = "annual",
      units = "degree days",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  
  new("Quantity",
      id = "aleafshed",
      name = "Number times leafs shed per year",
      type = "PFT",
      units = "",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "cton_leaf",
      name = "C:N leaf",
      type = "PFT",
      units = "ckgC/kgN",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "nmass",
      name = "Vegetation Nitrogen Mass",
      type = "PFT",
      units = "kgN/m^2",
      colours = viridis::viridis,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "ngases",
      name = "Annual Nitrogren Gases Emissions",
      type = "-",
      units = "kg/ha/year",
      colours = viridis::viridis,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "npool",
      name = "Nitrogen",
      type = "pools",
      units = "kgN/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "nuptake",
      name = "Nitrogen Uptake",
      type = "PFT",
      units = "kgN/ha",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "nsources",
      name = "Nitrogen Source",
      type = "annual",
      units = "gN/ha",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
 
  
  new("Quantity",
      id = "nflux",
      name = "Nitrogen Flux",
      type = "annual",
      units = "kgN/ha",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "nlitter",
      name = "Litter Nitrogen Mass",
      type = "PFT",
      units = "kgN/ha",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mprec",
      name = "Monthly Precipitation",
      type = "monthly",
      units = "mm",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mtemp",
      name = "Mean Monthly Temperature",
      type = "monthly",
      units = "deg C",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mwmass_stem",
      name = "Water Stored in Stem",
      type = "monthly",
      units = "kgH20/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mwmass_leaf",
      name = "Water Stored in Leaves",
      type = "monthly",
      units = "kgH20/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "bioclim_mtemps",
      name = "Bioclimactic Temperatures",
      type = "annual",
      units = "deg C",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS", "LPJ-GUESS-SPITFIRE")),
  
  
  #############################################################################################
  ############################# LPJ-GUESS-SPITFIRE QUANTITIES #################################
  #############################################################################################
  
  new("Quantity",
      id = "mfirefrac",
      name = "Monthly Burned Area Fraction",
      type = "monthly",
      units = "",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mtau_l",
      name = "Monthly Residence Time",
      type = "monthly",
      units = "mins",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "pyro_flux",
      name = "Pyrogenic Emmisions",
      type = "irregular",
      units = "kg species/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireintens",
      name = "Monthly Fire Intensity",
      type = "monthly",
      units = "kW/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mlivegrass_fuel",
      name = "Mean Monthly Live Grass Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1hr_fuel",
      name = "Mean Monthly 1hr Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m10hr_fuel",
      name = "Mean Monthly 10hr Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m100hr_fuel",
      name = "Mean Monthly 100hr Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1000hr_fuel",
      name = "Mean Monthly 1000hr Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mlivegrass_cc",
      name = "Mean Monthly Live Grass Combustion Completeness",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1hr_cc",
      name = "Mean Monthly 1hr Combustion Completeness",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m10hr_cc",
      name = "Mean Monthly 10hr Combustion Completeness",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id ="m100hr_cc",
      name = "Mean Monthly 100hr Combustion Completeness",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "m1000hr_cc",
      name = "Mean Monthly 1000hr Combustion Completeness",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "afdays",
      name = "Fire Days per Year",
      type = "annual",
      units = "days",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mavenest",
      name = "Average Monthly Nesterov",
      type = "monthly",
      units = "",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mdlm_livegrass",
      name = "Monthly Litter Moisture of Live Grass",
      type = "monthly",
      units = "",
      colours = reversed.tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mdlm_deadfuel",
      name = "Monthly Litter Moisture of Dead Fuel",
      type = "monthly",
      units = "",
      colours = reversed.tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "meff_wind",
      name = "Monthly Effective Windspeed",
      type = "monthly",
      units = "m/min",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mnfdi",
      name = "Monthly Nesterov Fire Danger Index",
      type = "monthly",
      units = "m/min",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  
  new("Quantity",
      id = "mFBD",
      name = "Monthly Fuel Bulk Density",
      type = "monthly",
      units = "m^3/m^3",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mSAV",
      name = "Monthly Surface Area to Volume Ratio",
      type = "monthly",
      units = "m^2/m^3",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mMoE",
      name = "Monthly Moisture of Extinction",
      type = "monthly",
      units = "",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mmcont",
      name = "Monthly Fuel Moisture Content",
      type = "monthly",
      units = "",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfire_durat",
      name = "Monthly Fire Duration",
      type = "monthly",
      units = "mins",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mscorch_height",
      name = "Monthly Scorch Height",
      type = "monthly",
      units = "m",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mRoS",
      name = "Monthly Rate of Spread",
      type = "monthly",
      units = "m/min",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfire_size",
      name = "Monthly Fire Size",
      type = "monthly",
      units = "ha",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mhuman_ign",
      name = "Monthly average of human ignition rate",
      type = "monthly",
      units = "ign/day",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mlightning_ign",
      name = "Monthly average of lightning ignition rate",
      type = "monthly",
      units = "ign/day",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_duration",
      name = "Monthly Fire Duration (Fire Days Only)",
      type = "monthly",
      units = "mins",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_scorch_height",
      name = "Monthly Scorch Height (Fire Days Only)",
      type = "monthly",
      units = "m",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_intensity",
      name = "Monthly Fire Intensity (Fire Days Only)",
      type = "monthly",
      units = "kW/m",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_nesterov",
      name = "Monthly Nesterov (Fire Days Only)",
      type = "monthly",
      units = "",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfireday_residence_time",
      name = "Monthly Residence Time (Fire Days Only)",
      type = "monthly",
      units = "min",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "allocation_fails",
      name = "Monthly Allocation Fails",
      type = "annual",
      units = "days",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "allocation_iters",
      name = "Monthly Iteration To Allocation Fire",
      type = "annual",
      units = "days",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfuel",
      name = "Monthly Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfinefuel",
      name = "Monthly Fine Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mleaffuel",
      name = "Monthly Leaf Fuel",
      type = "monthly",
      units = "kgC/m^2",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  
  new("Quantity",
      id = "mfiredays",
      name = "Monthly sum of daily fire probabilites",
      type = "monthly",
      units = "days",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE")),
  
  new("Quantity",
      id = "mfiredaysfine",
      name = "Monthly sum of daily fire probabilites (based on fine fuel threshold)",
      type = "monthly",
      units = "days",
      colours = fields::tim.colors,
      model = c("LPJ-GUESS-SPITFIRE"))
  
)




